[project]
name = "ngsnap"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Ben Pedigo", email = "benjamindpedigo@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "neuroglancer>=2.41.2",
]

[build-system]
requires = ["uv_build>=0.11.3,<0.12.0"]
build-backend = "uv_build"



[tool.ruff.lint]
extend-select = [
    "ANN",
    "C90",
    "ERA",
    "F",
    "FURB",
    "I",
    "N",
    "NPY",
    "PERF",
    "PL",
    "PLE",
    "PLR",
    "PLW",
    "PTH",
    "SIM",
    "TRY",
    "UP",
]
ignore = ["PLC0415", "PLR0913", "PLR0917", "PLR2004", "PLW2901", "TRY003", "BLE001"]

[tool.ruff.format]
exclude = ["*.md"]

[dependency-groups]
dev = [
    "mypy>=2.3.1",
    "pytest>=9.1.1",
    "ruff>=0.16.6",
]
